package com.region.moudles.hospital.domain;


import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import com.alibaba.fastjson.annotation.JSONField;
import com.region.moudles.common.domain.BaseDomain;

/**
 * 住院医嘱明细表(hospital_order_item)
 * 
 * @author tz
 * @version 1.0.0 2020-06-03
 */
@Entity
@Table(name = "hospital_order_item")
public class HospitalOrderItem extends BaseDomain {
    /** 版本号 */
    private static final long serialVersionUID = -7587097635694829082L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    @Id
    private String id;

    /** 医嘱标识 */
    private String orderId;

    /** 医嘱性质("01:西药  02:中成药 03:中草药 04:卫生材料 05:治疗 06:检查 07:检验 08:手术 09:护理 10:病情 11:饮食 12:记事 99:其它诊疗") */
    private String orderChara;

    /** 医嘱内容 */
    private String orderContent;

    /** 药品分类代码 */
    private String drugClassCode;

    /** 药物编号/项目编号 */
    private String drugCode;

    /** 药物通用名 */
    private String drugCommonName;

    /** 药物名称/项目名称 */
    private String drugName;

    /** 规格 */
    private String spec;

    /** 单位 */
    private String unit;

    /** 数量 */
    private String quantity;

    /** 单位剂量 */
    private String unitDose;

    /** 医嘱用量 */
    private String orderDosage;

    /** 用药方式 */
    private String drugRoute;

    /** 执行频率 */
    private String drugFrequency;

    /** 用药数量 */
    private String drugQuantity;

    /** 药房单位 */
    private String dispensaryUnit;

    /** 下嘱日期 */
    @JSONField(format="yyyy-MM-dd")
    private Date prescribeDate;

    /** 申请天数 */
    private String applyDays;

    /** 领用数量 */
    private String userQuantity;

    /** 执行日期 */
    @JSONField(format="yyyy-MM-dd")
    private Date executeDate;

    /** 发药日期 */
    @JSONField(format="yyyy-MM-dd")
    private Date issueDate;

    /** 停嘱日期 */
    @JSONField(format="yyyy-MM-dd")
    private Date stopDate;

    /** 状态(0:取消 1:正常) */
    private String status;

    /** 取消原因 */
    private String cancelReason;

    /** 取消时间 */
    @JSONField(format="yyyy-MM-dd")
    private Date cancelTime;

    /** 取消医生代码 */
    private String doctorCode;

    /** 取消医生姓名 */
    private String doctorName;

    /** his内码 */
    private String hisOrderId;
    
    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取id
     * 
     * @return id
     */
    public String getId() {
        return this.id;
    }

    /**
     * 设置id
     * 
     * @param id
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * 获取医嘱标识
     * 
     * @return 医嘱标识
     */
    public String getOrderId() {
        return this.orderId;
    }

    /**
     * 设置医嘱标识
     * 
     * @param orderId
     *          医嘱标识
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     * 获取医嘱性质("01:西药  02:中成药 03:中草药 04:卫生材料 05:治疗 06:检查 07:检验 08:手术 09:护理 10:病情 11:饮食 12:记事 99:其它诊疗")
     * 
     * @return 医嘱性质("01
     */
    public String getOrderChara() {
        return this.orderChara;
    }

    /**
     * 设置医嘱性质("01:西药  02:中成药 03:中草药 04:卫生材料 05:治疗 06:检查 07:检验 08:手术 09:护理 10:病情 11:饮食 12:记事 99:其它诊疗")
     * 
     * @param orderChara
     *          医嘱性质("01
     */
    public void setOrderChara(String orderChara) {
        this.orderChara = orderChara;
    }

    /**
     * 获取医嘱内容
     * 
     * @return 医嘱内容
     */
    public String getOrderContent() {
        return this.orderContent;
    }

    /**
     * 设置医嘱内容
     * 
     * @param orderContent
     *          医嘱内容
     */
    public void setOrderContent(String orderContent) {
        this.orderContent = orderContent;
    }

    /**
     * 获取药品分类代码
     * 
     * @return 药品分类代码
     */
    public String getDrugClassCode() {
        return this.drugClassCode;
    }

    /**
     * 设置药品分类代码
     * 
     * @param drugClassCode
     *          药品分类代码
     */
    public void setDrugClassCode(String drugClassCode) {
        this.drugClassCode = drugClassCode;
    }

    /**
     * 获取药物编号/项目编号
     * 
     * @return 药物编号/项目编号
     */
    public String getDrugCode() {
        return this.drugCode;
    }

    /**
     * 设置药物编号/项目编号
     * 
     * @param drugCode
     *          药物编号/项目编号
     */
    public void setDrugCode(String drugCode) {
        this.drugCode = drugCode;
    }

    /**
     * 获取药物通用名
     * 
     * @return 药物通用名
     */
    public String getDrugCommonName() {
        return this.drugCommonName;
    }

    /**
     * 设置药物通用名
     * 
     * @param drugCommonName
     *          药物通用名
     */
    public void setDrugCommonName(String drugCommonName) {
        this.drugCommonName = drugCommonName;
    }

    /**
     * 获取药物名称/项目名称
     * 
     * @return 药物名称/项目名称
     */
    public String getDrugName() {
        return this.drugName;
    }

    /**
     * 设置药物名称/项目名称
     * 
     * @param drugName
     *          药物名称/项目名称
     */
    public void setDrugName(String drugName) {
        this.drugName = drugName;
    }

    /**
     * 获取规格
     * 
     * @return 规格
     */
    public String getSpec() {
        return this.spec;
    }

    /**
     * 设置规格
     * 
     * @param spec
     *          规格
     */
    public void setSpec(String spec) {
        this.spec = spec;
    }

    /**
     * 获取单位
     * 
     * @return 单位
     */
    public String getUnit() {
        return this.unit;
    }

    /**
     * 设置单位
     * 
     * @param unit
     *          单位
     */
    public void setUnit(String unit) {
        this.unit = unit;
    }

    /**
     * 获取数量
     * 
     * @return 数量
     */
    public String getQuantity() {
        return this.quantity;
    }

    /**
     * 设置数量
     * 
     * @param quantity
     *          数量
     */
    public void setQuantity(String quantity) {
        this.quantity = quantity;
    }

    /**
     * 获取单位剂量
     * 
     * @return 单位剂量
     */
    public String getUnitDose() {
        return this.unitDose;
    }

    /**
     * 设置单位剂量
     * 
     * @param unitDose
     *          单位剂量
     */
    public void setUnitDose(String unitDose) {
        this.unitDose = unitDose;
    }

    /**
     * 获取医嘱用量
     * 
     * @return 医嘱用量
     */
    public String getOrderDosage() {
        return this.orderDosage;
    }

    /**
     * 设置医嘱用量
     * 
     * @param orderDosage
     *          医嘱用量
     */
    public void setOrderDosage(String orderDosage) {
        this.orderDosage = orderDosage;
    }

    /**
     * 获取用药方式
     * 
     * @return 用药方式
     */
    public String getDrugRoute() {
        return this.drugRoute;
    }

    /**
     * 设置用药方式
     * 
     * @param drugRoute
     *          用药方式
     */
    public void setDrugRoute(String drugRoute) {
        this.drugRoute = drugRoute;
    }

    /**
     * 获取执行频率
     * 
     * @return 执行频率
     */
    public String getDrugFrequency() {
        return this.drugFrequency;
    }

    /**
     * 设置执行频率
     * 
     * @param drugFrequency
     *          执行频率
     */
    public void setDrugFrequency(String drugFrequency) {
        this.drugFrequency = drugFrequency;
    }

    /**
     * 获取用药数量
     * 
     * @return 用药数量
     */
    public String getDrugQuantity() {
        return this.drugQuantity;
    }

    /**
     * 设置用药数量
     * 
     * @param drugQuantity
     *          用药数量
     */
    public void setDrugQuantity(String drugQuantity) {
        this.drugQuantity = drugQuantity;
    }

    /**
     * 获取药房单位
     * 
     * @return 药房单位
     */
    public String getDispensaryUnit() {
        return this.dispensaryUnit;
    }

    /**
     * 设置药房单位
     * 
     * @param dispensaryUnit
     *          药房单位
     */
    public void setDispensaryUnit(String dispensaryUnit) {
        this.dispensaryUnit = dispensaryUnit;
    }

    /**
     * 获取下嘱日期
     * 
     * @return 下嘱日期
     */
    public Date getPrescribeDate() {
        return this.prescribeDate;
    }

    /**
     * 设置下嘱日期
     * 
     * @param prescribeDate
     *          下嘱日期
     */
    public void setPrescribeDate(Date prescribeDate) {
        this.prescribeDate = prescribeDate;
    }

    /**
     * 获取申请天数
     * 
     * @return 申请天数
     */
    public String getApplyDays() {
        return this.applyDays;
    }

    /**
     * 设置申请天数
     * 
     * @param applyDays
     *          申请天数
     */
    public void setApplyDays(String applyDays) {
        this.applyDays = applyDays;
    }

    /**
     * 获取领用数量
     * 
     * @return 领用数量
     */
    public String getUserQuantity() {
        return this.userQuantity;
    }

    /**
     * 设置领用数量
     * 
     * @param userQuantity
     *          领用数量
     */
    public void setUserQuantity(String userQuantity) {
        this.userQuantity = userQuantity;
    }

    /**
     * 获取执行日期
     * 
     * @return 执行日期
     */
    public Date getExecuteDate() {
        return this.executeDate;
    }

    /**
     * 设置执行日期
     * 
     * @param executeDate
     *          执行日期
     */
    public void setExecuteDate(Date executeDate) {
        this.executeDate = executeDate;
    }

    /**
     * 获取发药日期
     * 
     * @return 发药日期
     */
    public Date getIssueDate() {
        return this.issueDate;
    }

    /**
     * 设置发药日期
     * 
     * @param issueDate
     *          发药日期
     */
    public void setIssueDate(Date issueDate) {
        this.issueDate = issueDate;
    }

    /**
     * 获取停嘱日期
     * 
     * @return 停嘱日期
     */
    public Date getStopDate() {
        return this.stopDate;
    }

    /**
     * 设置停嘱日期
     * 
     * @param stopDate
     *          停嘱日期
     */
    public void setStopDate(Date stopDate) {
        this.stopDate = stopDate;
    }

    /**
     * 获取状态(0:取消 1:正常)
     * 
     * @return 状态(0
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * 设置状态(0:取消 1:正常)
     * 
     * @param status
     *          状态(0
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * 获取取消原因
     * 
     * @return 取消原因
     */
    public String getCancelReason() {
        return this.cancelReason;
    }

    /**
     * 设置取消原因
     * 
     * @param cancelReason
     *          取消原因
     */
    public void setCancelReason(String cancelReason) {
        this.cancelReason = cancelReason;
    }

    /**
     * 获取取消时间
     * 
     * @return 取消时间
     */
    public Date getCancelTime() {
        return this.cancelTime;
    }

    /**
     * 设置取消时间
     * 
     * @param cancelTime
     *          取消时间
     */
    public void setCancelTime(Date cancelTime) {
        this.cancelTime = cancelTime;
    }

    /**
     * 获取取消医生代码
     * 
     * @return 取消医生代码
     */
    public String getDoctorCode() {
        return this.doctorCode;
    }

    /**
     * 设置取消医生代码
     * 
     * @param doctorCode
     *          取消医生代码
     */
    public void setDoctorCode(String doctorCode) {
        this.doctorCode = doctorCode;
    }

    /**
     * 获取取消医生姓名
     * 
     * @return 取消医生姓名
     */
    public String getDoctorName() {
        return this.doctorName;
    }

    /**
     * 设置取消医生姓名
     * 
     * @param doctorName
     *          取消医生姓名
     */
    public void setDoctorName(String doctorName) {
        this.doctorName = doctorName;
    }

    /**
     * 获取his内码
     * 
     * @return his内码
     */
    public String getHisOrderId() {
        return this.hisOrderId;
    }

    /**
     * 设置his内码
     * 
     * @param hisOrderId
     *          his内码
     */
    /* This code was generated by TableGo tools, mark 2 end. */
}