package com.region.moudles.hospital.domain;


import java.util.Date;
import java.util.List;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.alibaba.fastjson.annotation.JSONField;
import com.region.moudles.common.domain.BaseDomain;

/**
 * 住院医嘱基本信息表(hospital_order)
 * 
 * @author tz
 * @version 1.0.0 2020-06-03
 */
@Entity
@Table(name = "hospital_order")
public class HospitalOrder extends BaseDomain {
    /** 版本号 */
    private static final long serialVersionUID = 1081983508180933913L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    @Id
    private String id;

    /** 医院编码 */
    private String orgCode;

    /** 医院名称 */
    private String orgName;

    /** 患者姓名 */
    private String name;

    /** 身份证号 */
    private String sfzh;

    /** 住院号 */
    private String admissionNum;

    /** 本次住院标识号 */
    private String admissionId;

    /** 科室代码 */
    private String depCode;

    /** 科室名称 */
    private String depName;

    /** 住院次数（次） */
    private String inpatientTimes;

    /** 病室 */
    private String ward;

    /** 床号 */
    private String sickbedNum;

    /** 活动发生时间 */
    @JSONField(format="yyyy-MM-dd")
    private Date effectiveTime;

    /** 所属行政区划 */
    private String districtAddress;

    /** 医嘱类型("1:长期医嘱 2:临时医嘱 3:长期备用医嘱 4:临时备用医嘱 9:其他医嘱") */
    private String orderType;

    /** his内码 */
    private String hisId;
    
    @Transient
    private List<HospitalOrderItem> oiList;
    @Transient
    private List<HospitalOrderDoctor> oiDoctorList;
    @Transient
    private List<HospitalOrderDepartment> oiDepList;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取id
     * 
     * @return id
     */
    public String getId() {
        return this.id;
    }

    /**
     * 设置id
     * 
     * @param id
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * 获取医院编码
     * 
     * @return 医院编码
     */
    public String getOrgCode() {
        return this.orgCode;
    }

    /**
     * 设置医院编码
     * 
     * @param orgCode
     *          医院编码
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode;
    }

    /**
     * 获取医院名称
     * 
     * @return 医院名称
     */
    public String getOrgName() {
        return this.orgName;
    }

    /**
     * 设置医院名称
     * 
     * @param orgName
     *          医院名称
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    /**
     * 获取患者姓名
     * 
     * @return 患者姓名
     */
    public String getName() {
        return this.name;
    }

    /**
     * 设置患者姓名
     * 
     * @param name
     *          患者姓名
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * 获取身份证号
     * 
     * @return 身份证号
     */
    public String getSfzh() {
        return this.sfzh;
    }

    /**
     * 设置身份证号
     * 
     * @param sfzh
     *          身份证号
     */
    public void setSfzh(String sfzh) {
        this.sfzh = sfzh;
    }

    /**
     * 获取住院号
     * 
     * @return 住院号
     */
    public String getAdmissionNum() {
        return this.admissionNum;
    }

    /**
     * 设置住院号
     * 
     * @param admissionNum
     *          住院号
     */
    public void setAdmissionNum(String admissionNum) {
        this.admissionNum = admissionNum;
    }

    /**
     * 获取本次住院标识号
     * 
     * @return 本次住院标识号
     */
    public String getAdmissionId() {
        return this.admissionId;
    }

    /**
     * 设置本次住院标识号
     * 
     * @param admissionId
     *          本次住院标识号
     */
    public void setAdmissionId(String admissionId) {
        this.admissionId = admissionId;
    }

    /**
     * 获取科室代码
     * 
     * @return 科室代码
     */
    public String getDepCode() {
        return this.depCode;
    }

    /**
     * 设置科室代码
     * 
     * @param depCode
     *          科室代码
     */
    public void setDepCode(String depCode) {
        this.depCode = depCode;
    }

    /**
     * 获取科室名称
     * 
     * @return 科室名称
     */
    public String getDepName() {
        return this.depName;
    }

    /**
     * 设置科室名称
     * 
     * @param depName
     *          科室名称
     */
    public void setDepName(String depName) {
        this.depName = depName;
    }

    /**
     * 获取住院次数（次）
     * 
     * @return 住院次数（次）
     */
    public String getInpatientTimes() {
        return this.inpatientTimes;
    }

    /**
     * 设置住院次数（次）
     * 
     * @param inpatientTimes
     *          住院次数（次）
     */
    public void setInpatientTimes(String inpatientTimes) {
        this.inpatientTimes = inpatientTimes;
    }

    /**
     * 获取病室
     * 
     * @return 病室
     */
    public String getWard() {
        return this.ward;
    }

    /**
     * 设置病室
     * 
     * @param ward
     *          病室
     */
    public void setWard(String ward) {
        this.ward = ward;
    }

    /**
     * 获取床号
     * 
     * @return 床号
     */
    public String getSickbedNum() {
        return this.sickbedNum;
    }

    /**
     * 设置床号
     * 
     * @param sickbedNum
     *          床号
     */
    public void setSickbedNum(String sickbedNum) {
        this.sickbedNum = sickbedNum;
    }

    /**
     * 获取活动发生时间
     * 
     * @return 活动发生时间
     */
    public Date getEffectiveTime() {
        return this.effectiveTime;
    }

    /**
     * 设置活动发生时间
     * 
     * @param effectiveTime
     *          活动发生时间
     */
    public void setEffectiveTime(Date effectiveTime) {
        this.effectiveTime = effectiveTime;
    }

    public String getDistrictAddress() {
		return districtAddress;
	}

	public void setDistrictAddress(String districtAddress) {
		this.districtAddress = districtAddress;
	}

	/**
     * 获取医嘱类型("1:长期医嘱 2:临时医嘱 3:长期备用医嘱 4:临时备用医嘱 9:其他医嘱")
     * 
     * @return 医嘱类型("1
     */
    public String getOrderType() {
        return this.orderType;
    }

    /**
     * 设置医嘱类型("1:长期医嘱 2:临时医嘱 3:长期备用医嘱 4:临时备用医嘱 9:其他医嘱")
     * 
     * @param orderType
     *          医嘱类型("1
     */
    public void setOrderType(String orderType) {
        this.orderType = orderType;
    }

    /**
     * 获取his内码
     * 
     * @return his内码
     */
    public String getHisId() {
        return this.hisId;
    }

    /**
     * 设置his内码
     * 
     * @param hisId
     *          his内码
     */
    public void setHisId(String hisId) {
        this.hisId = hisId;
    }

	public List<HospitalOrderItem> getOiList() {
		return oiList;
	}

	public void setOiList(List<HospitalOrderItem> oiList) {
		this.oiList = oiList;
	}

	public List<HospitalOrderDoctor> getOiDoctorList() {
		return oiDoctorList;
	}

	public void setOiDoctorList(List<HospitalOrderDoctor> oiDoctorList) {
		this.oiDoctorList = oiDoctorList;
	}

	public List<HospitalOrderDepartment> getOiDepList() {
		return oiDepList;
	}

	public void setOiDepList(List<HospitalOrderDepartment> oiDepList) {
		this.oiDepList = oiDepList;
	}



    /* This code was generated by TableGo tools, mark 2 end. */
}