package com.region.moudles.hospital.domain;


import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import com.region.moudles.common.domain.BaseDomain;

/**
 * 住院医嘱明细-科室信息表(hospital_oi_department)
 * 
 * @author tz
 * @version 1.0.0 2020-06-03
 */
@Entity
@Table(name = "hospital_order_department")
public class HospitalOrderDepartment extends BaseDomain {
    /** 版本号 */
    private static final long serialVersionUID = -4786875017370850870L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    @Id
    private String id;

    /** 医嘱明细标识 */
    private String oiId;

    /** 科室类型（"1:入院科别 10:停嘱执行科室 11:收费科室 12:入库科室 2:出院科别 3:转科科别 4:门诊科别 5:急诊科别 6:住院科室 7:下嘱科室 8:医嘱执行科室 9:停嘱科室"） */
    private String depType;

    /** 科室编码 */
    private String depCode;

    /** 科室名称 */
    private String depName;

    /** his科室内码 */
    private String hisOiId;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取id
     * 
     * @return id
     */
    public String getId() {
        return this.id;
    }

    /**
     * 设置id
     * 
     * @param id
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * 获取医嘱明细标识
     * 
     * @return 医嘱明细标识
     */
    public String getOiId() {
        return this.oiId;
    }

    /**
     * 设置医嘱明细标识
     * 
     * @param oiId
     *          医嘱明细标识
     */
    public void setOiId(String oiId) {
        this.oiId = oiId;
    }

    /**
     * 获取科室类型（"1:入院科别 10:停嘱执行科室 11:收费科室 12:入库科室 2:出院科别 3:转科科别 4:门诊科别 5:急诊科别 6:住院科室 7:下嘱科室 8:医嘱执行科室 9:停嘱科室"）
     * 
     * @return 科室类型（"1
     */
    public String getDepType() {
        return this.depType;
    }

    /**
     * 设置科室类型（"1:入院科别 10:停嘱执行科室 11:收费科室 12:入库科室 2:出院科别 3:转科科别 4:门诊科别 5:急诊科别 6:住院科室 7:下嘱科室 8:医嘱执行科室 9:停嘱科室"）
     * 
     * @param depType
     *          科室类型（"1
     */
    public void setDepType(String depType) {
        this.depType = depType;
    }

    /**
     * 获取科室编码
     * 
     * @return 科室编码
     */
    public String getDepCode() {
        return this.depCode;
    }

    /**
     * 设置科室编码
     * 
     * @param depCode
     *          科室编码
     */
    public void setDepCode(String depCode) {
        this.depCode = depCode;
    }

    /**
     * 获取科室名称
     * 
     * @return 科室名称
     */
    public String getDepName() {
        return this.depName;
    }

    /**
     * 设置科室名称
     * 
     * @param depName
     *          科室名称
     */
    public void setDepName(String depName) {
        this.depName = depName;
    }

    /**
     * 获取his科室内码
     * 
     * @return his科室内码
     */
    public String getHisOiId() {
        return this.hisOiId;
    }

    /**
     * 设置his科室内码
     * 
     * @param hisOiId
     *          his科室内码
     */
    public void setHisOiId(String hisOiId) {
        this.hisOiId = hisOiId;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}